SELECT ?film WHERE { ?film wdt:P57 wd:Q311263 . ?film wdt:P58 wd:Q311263 . ?film wdt:P577 ?releaseDate . ?releaseDate >= "1984-01-01T00:00:00Z"^^xsd:dateTime . ?releaseDate < "1985-01-01T00:00:00Z"^^xsd:dateTime }
