SELECT ?goalkeeper ?match WHERE {
  ?match wdt:P1923 wd:Q164134 .
  ?match wdt:P1923 wd:Q166776 .
  ?goalkeeper wdt:P413 wd:Q10789 .
  ?goalkeeper wdt:P1082 ?match .
  ?goalkeeper wdt:P5700 ?saveCount .
  FILTER ( ?saveCount = 15 )
}
