SELECT ?character ?characterLabel WHERE {
  wd:Q129978 wdt:P161 wd:Q55604025 .
  wd:Q129978 wdt:P453 ?character .
  ?character rdfs:label ?characterLabel .
  FILTER ( LANG( ?characterLabel ) = 'en' )
}
