# -*- coding: utf-8 -*-
"""Wikidata-LLM-Inconsistencies.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x4qYYppaUixcFDAlyrXogFVtV4-C7pUs
"""

OLLAMA_URL = "https://mcp-kg-ollama.tools.eurecom.fr/"
OLLAMA_TOKEN = "bWNwLWtnLW9sbGFtYTpiMTZhMjhlZGFhMGFmMWU1ZDkxYThkNGY2ZTE5ZjJkZTExNjAwYTBhMzcyN2NkOGIwYWM2NWEwZTk3MzFiYzgy"

import ollama
import requests
import json
from typing import Optional, Dict, List, Any
from pathlib import Path
import pandas as pd
import time
import csv
from ollama import ResponseError

headers = {
    "Authorization": f"Basic {OLLAMA_TOKEN}"
}
client = ollama.Client(host=OLLAMA_URL, headers=headers)


def get_wikidata_properties_old(qid: str) -> Dict[str, Any]:
    """
    Query Wikidata via SPARQL to retrieve only meaningful properties for a given QID.
    Filters out identifier/reference properties that are not useful for fact-checking.

    Args:
        qid: Wikidata QID (e.g., "Q188652")

    Returns:
        Dictionary containing filtered properties and their values in English
    """
    # Ensure QID format
    if not qid.startswith("Q"):
        qid = f"Q{qid}"

    # SPARQL query to get entity data with property labels
    # Excludes ExternalId, Url, and String properties which are mostly identifiers
    sparql_query = f"""
    SELECT ?property ?propertyLabel ?value ?valueLabel
    WHERE {{
      wd:{qid} ?p ?value .
      ?property wikibase:directClaim ?p ;
                rdfs:label ?propertyLabel ;
                wikibase:propertyType ?propertyType .
      FILTER(LANG(?propertyLabel) = "en")

      # Filter out identifier properties
      FILTER(
        ?propertyType != wikibase:ExternalId &&
        ?propertyType != wikibase:Url &&
        ?propertyType != wikibase:String
      )

      # Get label for items
      OPTIONAL {{
        ?value rdfs:label ?valueLabel .
        FILTER(LANG(?valueLabel) = "en")
      }}
    }}
    ORDER BY ?propertyLabel
    """

    url = "https://query.wikidata.org/sparql"
    wikidata_headers = {
        "User-Agent": "Mozilla/5.0 (compatible; WikidataValidator/1.0; +http://example.com/bot)",
        "Accept": "application/json"
    }
    params = {
        "query": sparql_query,
        "format": "json"
    }

    try:
        response = requests.get(url, params=params, headers=wikidata_headers, timeout=20)
        print(f"Status code: {response.status_code}")
        print(f"Response headers: {response.headers}")
        response.raise_for_status()
        data = response.json()

        print(f"Réponse JSON complète: {json.dumps(data, indent=2)[:500]}")  # Premiers 500 caractères
        
        if "results" in data and "bindings" in data["results"]:
            print(f"Nombre de bindings: {len(data['results']['bindings'])}")
            if len(data['results']['bindings']) > 0:
                print(f"Premier résultat: {data['results']['bindings'][0]}")
        else:
            print(f"Structure inattendue de la réponse: {data.keys()}")

        print(f"Réponse reçue: {len(data.get('results', {}).get('bindings', []))} résultats")

        # Group results by property
        properties_dict = {}

        if "results" in data and "bindings" in data["results"]:
            for binding in data["results"]["bindings"]:
                prop_label = binding.get("propertyLabel", {}).get("value", "")

                value = binding.get("value", {}).get("value", "")
                value_label = binding.get("valueLabel", {}).get("value", "")

                # Format value with label if available
                if value_label:
                    formatted_value = f"{value_label} ({value.split('/')[-1]})"
                else:
                    formatted_value = value

                # Group by property label for readability
                if prop_label not in properties_dict:
                    properties_dict[prop_label] = []

                if formatted_value not in properties_dict[prop_label]:
                    properties_dict[prop_label].append(formatted_value)

        if not properties_dict:
            return None

        time.sleep(1)
        return properties_dict

    except requests.RequestException as e:
        print(f"Error querying Wikidata SPARQL: {e}")
        return None

    except requests.exceptions.Timeout:
        print(f"ERROR")
        return None

    except ResponseError as e:
        print(f"Error")
        return None

    except Exception as e:
        print(f"Unexpected error")
        return None



def get_wikidata_properties(qid: str) -> Dict[str, Any]:
    """
    Query Wikidata via SPARQL to retrieve meaningful properties for a given QID.
    """
    # Nettoyer et formater le QID
    qid = str(qid).strip()
    if not qid.startswith("Q"):
        qid = f"Q{qid}"
    
    # SPARQL query - VERSION SIMPLIFIÉE pour tester
    sparql_query = f"""
    SELECT ?property ?propertyLabel ?value ?valueLabel
    WHERE {{
      wd:{qid} ?p ?value .
      ?property wikibase:directClaim ?p .
      
      # Récupérer les labels
      SERVICE wikibase:label {{ 
        bd:serviceParam wikibase:language "en" .
      }}
    }}
    LIMIT 100
    """

    url = "https://query.wikidata.org/sparql"
    wikidata_headers = {
        "User-Agent": "WikidataValidator/1.0",
        "Accept": "application/json"
    }
    params = {
        "query": sparql_query,
        "format": "json"
    }

    try:
        response = requests.get(url, params=params, headers=wikidata_headers, timeout=30)
        print(f"Status code: {response.status_code}")
        
        response.raise_for_status()
        data = response.json()

        # Vérifier la structure de la réponse
        bindings = data.get("results", {}).get("bindings", [])
        print(f"Nombre de résultats trouvés: {len(bindings)}")
        
        if len(bindings) == 0:
            print(f"Aucune propriété trouvée pour {qid}")
            print(f"Vérifiez que le QID existe sur Wikidata: https://www.wikidata.org/wiki/{qid}")
            return None

        # Afficher les premiers résultats pour debug
        #if len(bindings) > 0:
        #    print(f"Premier résultat: {bindings[0]}")

        # Grouper les résultats par propriété
        properties_dict = {}

        for binding in bindings:
            prop_label = binding.get("propertyLabel", {}).get("value", "Unknown Property")
            value = binding.get("value", {}).get("value", "")
            value_label = binding.get("valueLabel", {}).get("value", "")

            # Formater la valeur
            if value_label and value_label != value:
                formatted_value = f"{value_label}"
            else:
                # Extraire juste l'ID si c'est une URL Wikidata
                if "wikidata.org" in value:
                    formatted_value = value.split('/')[-1]
                else:
                    formatted_value = value

            # Grouper par propriété
            if prop_label not in properties_dict:
                properties_dict[prop_label] = []

            if formatted_value not in properties_dict[prop_label]:
                properties_dict[prop_label].append(formatted_value)

        print(f"{len(properties_dict)} propriétés uniques trouvées")
        #print(f"Exemples: {list(properties_dict.keys())[:5]}")
        
        time.sleep(1)
        return properties_dict

    except requests.exceptions.Timeout:
        print(f"Timeout lors de la requête Wikidata pour {qid}")
        return None
    
    except requests.RequestException as e:
        print(f"Erreur réseau Wikidata: {e}")
        return None
    
    except Exception as e:
        print(f"Erreur inattendue: {type(e).__name__}: {e}")
        return None


def validate_answer_with_llm(
    row
) -> Dict[str, Any]:
    """
    Use LLM to validate if an answer matches Wikidata properties for a given QID.

    Args:
        qid: Wikidata QID
        question: Original question
        answer: Dict with 'id' and 'label' keys
        model: LLM model to use (default: ministral-3:14b)

    Returns:
        Dict containing validation result and matching property (if found)
    """
    qid = row.get("Question_entity","")
    question = row.get("Question","")
    answer = row.get("CompMix_answer_label","")
    model="ministral-3:14b"

    print(f"\n{'='*70}")
    print(f"DEBUG - QID brut: '{qid}'")
    print(f"Question: {question}")
    print(f"Réponse attendue: {answer}")
    print(f"{'='*70}")

    # Step 1: Get Wikidata properties (filtered)
    print(f"Fetching Wikidata properties for {qid}...")
    properties = get_wikidata_properties(qid)

    if properties is None:
        return {
            "qid": qid,
            "question": question,
            "answer": answer,
            "validation_result": {"found": False, "confidence": "low", "reasoning": "No properties found"},
            "wikidata_properties_count": 0
        }

    print(f"{len(properties)} propriétés trouvées")
    print(f"Propriétés: {list(properties.keys())[:5]}...")  # Affiche les 5 premières


    # Format properties for LLM
    properties_text = json.dumps(properties, indent=2, ensure_ascii=False)

    # Step 2: Query LLM with structured output
    prompt = f"""You are a fact-checking assistant. Analyze whether the given answer matches the provided Wikidata properties.

Question: {question}
Answer: {answer}

Available Wikidata Properties and Values:
{properties_text}

Determine if the answer is present in the properties list. If it is, identify the exact property that contains this answer. Return a JSON response with your findings."""

    response_format = {
        "type": "object",
        "properties": {
            "found": {
                "type": "boolean",
                "description": "Whether the answer was found in the properties"
            },
            "matching_property": {
                "type": "string",
                "description": "The property name that contains the answer (if found)"
            },
            "matching_value": {
                "type": "string",
                "description": "The exact matching value from the properties"
            },
            "confidence": {
                "type": "string",
                "enum": ["high", "medium", "low"],
                "description": "Confidence level of the match"
            },
            "reasoning": {
                "type": "string",
                "description": "Explanation of the validation result"
            }
        },
        "required": ["found", "confidence", "reasoning"]
    }

    try:
        print(f"Querying {model} for validation...")
        llm_response = client.generate(
            model=model,
            prompt=prompt,
            format=response_format,
            stream=False
        )

        # Parse the LLM response
        result = json.loads(llm_response.response)

        return {
            "qid": qid,
            "question": question,
            "answer": answer,
            "validation_result": result,
            "wikidata_properties_count": len(properties)
        }

    except json.JSONDecodeError as e:
        print(f"Error parsing LLM response: {e}")
        return {
            "qid": qid,
            "question": question,
            "answer": answer,
            "error": "Failed to parse LLM response",
            "raw_response": llm_response.response if 'llm_response' in locals() else None
        }


# Example usage
'''qid = "Q724455"
question = "Who is the screenwriter of the Rocky movie?"
answer = { "id": "Q40026", "label": "Sylvester Stallone" }

result = validate_answer_with_llm(qid, question, answer)
print(json.dumps(result, indent=2, ensure_ascii=False))'''




def main() -> None:
    base = Path(__file__).resolve().parent.parent
    csv_path = base / "Compix@Grasp/Finding_Inconsistency/sample_contrast.csv"

    df = pd.read_csv(csv_path)
    #result=df.apply(validate_answer_with_llm, axis=1)
    #df["LLM_result"] = result["validation_result"]["found"]

    #df.to_csv(csv_path, index=False)
      
    if "LLM_result" not in df.columns:
        df["LLM_result"] = None
    
    for index, row in df.iterrows():
        # Sauter si déjà traité
        if pd.notna(row["LLM_result"]):
            print(f"Ligne {index + 1}/{len(df)} déjà traitée, on passe...")
            continue
        
        print(f"\nTraitement de la ligne {index + 1}/{len(df)}...")
        
        try:
            result = validate_answer_with_llm(row)
            found_status = result["validation_result"]["found"]
            df.at[index, "LLM_result"] = found_status
            
        except requests.exceptions.Timeout:
            print(f"Timeout pour la ligne {index + 1}")
            df.at[index, "LLM_result"] = "TIMEOUT_ERROR"
            
        except Exception as e:
            print(f"Erreur pour la ligne {index + 1}: {e}")
            df.at[index, "LLM_result"] = "ERROR"
        
        # Sauvegarder après chaque ligne
        df.to_csv(csv_path, index=False)
        
        # Pause entre chaque requête
        time.sleep(2)

if __name__ == "__main__":
    main()


'''df = pd.read_csv(OUT_CSV)

if "LLM_result" not in df.columns:
    df["LLM_result"] = None


for index, row in df.iterrows():
    # Si la case 'LLM_result' n'est pas vide (déjà traitée), on saute
    if pd.notna(row["LLM_result"]):
        continue
    
    print(f"\nTraitement de la ligne {index + 1}/{len(df)}...")
    
    qid = row["question_id"]
    question = row["question"]
    answer = row["answer_label"]
    try : 
        result = validate_answer_with_llm(qid, question, answer)
        found_status = result["validation_result"]["found"]
        df.at[index, "LLM_result"] = found_status

    except requests.exceptions.Timeout:
        df.at[index, "LLM_result"] = "TIMEOUT_ERROR"
        
    except Exception as e:
        df.at[index, "LLM_result"] = "ERROR"

    df.to_csv(OUT_CSV, index=False)
    
    # Pause entre chaque ligne pour ne pas surcharger l'API
    time.sleep(2)
'''