PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT ?team ?teamLabel WHERE {
  wd:Q184586 wdt:P54 ?team .
  ?team wdt:P585 "2020" ^^ xsd:date .
  FILTER ( ?team != wd:Q8682 )
}
