PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT ?franchise WHERE {
  ?franchise wdt:P31 wd:Q241163 .
  ?franchise wdt:P4969 ?movie .
  ?movie wdt:P1851 'live action movie' @en
}
