PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wd: <http://www.wikidata.org/entity/>
SELECT ?actor ?label WHERE {
  wd:Q108946 wdt:P161 ?actor .
  ?actor rdfs:label ?label .
}
