PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT ?year WHERE {
  wd:Q2831 wdt:P585 ?date .
  ?date rdf:value ?value .
  ?value rdf:type xsd:integer .
  BIND( ?value AS ?year )
}
