PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT ?actor ?label WHERE {
  wd:Q212135 wdt:P166 ?actor .
  ?actor rdfs:label ?label .
  FILTER ( LANG( ?label ) = "en" )
}
ORDER BY ?label
