PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT ?movie ?director WHERE {
  ?movie wdt:P57 ?director .
  ?movie wdt:P136 wd:Q2080591 .
  FILTER ( ?director = wd:Q129079 )
}
