PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?book WHERE {
  ?book wdt:P179 wd:Q213167 .
  ?book rdfs:label ?label .
  FILTER ( CONTAINS( STR( ?label ) , "The Sea of Monsters" ) )
}
