PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?person ( rdfs:label AS ?label ) WHERE {
  ?person wdt:P31 wd:Q6186746
}
