PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT ?book ?publicationDate WHERE {
  ?book wdt:P577 ?publicationDate .
  ?book wdt:P921 wd:Q280898
}
