PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT ?series ?episodeCount WHERE {
  ?series wdt:P31 wd:Q5398426 .
  ?series wdt:P1113 ?episodeCount .
  FILTER ( STRSTARTS( STR( ?series ) , 'Only Connect' ) )
}
