PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wd: <http://www.wikidata.org/entity/>
SELECT ?award WHERE {
  wd:Q483325 wdt:P166 ?award .
  ?award wdt:P166 ?awardType .
  FILTER ( CONTAINS( STR( ?awardType ) , 'Annie Award for Voice Acting' ) )
}
