SELECT ?character ?actor WHERE {
  ?character wdt:P175 ?actor .
  ?actor rdfs:label ?actorLabel .
  FILTER ( LANG( ?actorLabel ) = 'en' ) .
  FILTER ( CONTAINS( STR( ?actorLabel ) , 'Sigourney Weaver' ) )
}
