PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wd: <http://www.wikidata.org/entity/>
SELECT ?book WHERE {
  wd:Q1339580 wdt:P527 ?book .
  ?book wdt:P1476 "Diary of a Wimpy Kid: Rodrick Rules"
}
