PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wd: <http://www.wikidata.org/entity/>
SELECT ?album ?releaseDate WHERE {
  wd:Q181826 wdt:P577 ?releaseDate .
  wd:Q199585 wdt:P577 ?releaseDate .
}
