PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wd: <http://www.wikidata.org/entity/>
SELECT ?movie ?movieLabel ?publicationDate WHERE {
  VALUES ?movie {
    wd:Q105598 wd:Q105993 wd:Q106871 wd:Q50861
  }
  ?movie wdt:P577 ?publicationDate .
}
ORDER BY ?publicationDate
