PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?award ?label WHERE {
  wd:Q23215 wdt:P166 ?award .
  ?award rdfs:label ?label .
  FILTER ( LANG( ?label ) = 'en' )
}
