SELECT ?performance ?label WHERE {
  ?performance wdt:P31 wd:Q106807719 .
  ?performance rdfs:label ?label .
  FILTER ( LCASE( SUBSTR( ?label , STRLEN( ?label ) - 34 ) ) = "candle in the wind goodbye england's rose" )
}
