PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?film ?novel WHERE {
  ?film wdt:P144 ?novel .
  ?film rdfs:label "Little Women" @en .
  ?novel rdfs:label "Little Women" @en .
  FILTER ( lang( ?film ) = "en" && lang( ?novel ) = "en" )
}
