PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?author ?novel WHERE {
  ?novel wdt:P170 ?author .
  ?novel wdt:P577 ?date .
  ?novel rdfs:label "Little Women" @en
}
