PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT ?televisionShow WHERE {
  wd:Q37079 wdt:P1441 ?televisionShow .
  ?televisionShow wdt:P31 wd:Q11361 .
}
