PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?motherActor WHERE {
  ?motherActor wd:P106 ?occupation .
  ?motherActor rdfs:label ?motherActorLabel .
  ?motherActor rdfs:label 'Lila A. Nair' .
}
