PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wd: <http://www.wikidata.org/entity/>
SELECT ?actress WHERE {
  wd:Q183513 wdt:P161 ?actor .
  ?actor wdt:P106 wd:Q1799459 .
  ?actress wdt:P106 wd:Q1799459
}
