PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wd: <http://www.wikidata.org/entity/>
SELECT ?book ?publicationDate WHERE {
  ?book wdt:P1433 wd:Q1431868 .
  ?book wdt:P577 ?publicationDate
}
