PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?name WHERE {
  ?entity wdt:P31 wd:Q19053825 .
  ?entity rdfs:label "Atticus Finch" @en
}
