PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?book ?publicationDate WHERE {
  ?book wdt:P577 ?publicationDate .
  ?book wdt:P136 wd:Q1027525 .
  ?book rdfs:label "Kingdom Come" @en
}
