PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT ?event WHERE {
  wd:Q334526 wdt:P1344 ?event .
  ?event wdt:P31 wd:Q159821 .
}
ORDER BY ?event
LIMIT 1
