PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wd: <http://www.wikidata.org/entity/>
SELECT ?organization ?position ?date WHERE {
  wd:Q4225496 wdtp:P488 ?organization .
  ?organization wdt:P488 wd:Q4225496 .
  ?organization wdt:P571 ?date .
  FILTER ( ?date >= '2019-01-01' && ?date < '2022-01-01' )
}
